import { Property, PropertyCategory, ThemeConfig } from './types';

export const THEMES: Record<PropertyCategory, ThemeConfig> = {
  [PropertyCategory.BEACH]: { primary: '#00d2d3', gradientFrom: '#00d2d3', gradientTo: '#1dd1a1' },
  [PropertyCategory.ADVENTURE]: { primary: '#10ac84', gradientFrom: '#10ac84', gradientTo: '#badb75' },
  [PropertyCategory.CITY]: { primary: '#ff9f43', gradientFrom: '#ff9f43', gradientTo: '#ffc107' },
  [PropertyCategory.HANOI]: { primary: '#ee5253', gradientFrom: '#ee5253', gradientTo: '#ff726d' },
  [PropertyCategory.BANGKOK]: { primary: '#5f27cd', gradientFrom: '#5f27cd', gradientTo: '#9d7cdb' },
  [PropertyCategory.MANILA]: { primary: '#cd9eff', gradientFrom: '#cd9eff', gradientTo: '#f3e5f5' }
};

export const PROPERTIES: Property[] = [
  { id: 'koh-rong', name: 'Koh Rong', country: 'Cambodia', category: PropertyCategory.BEACH, handle: 'kohrong', slug: 'kohrong-mother', whatsappUrl: 'https://chat.whatsapp.com/JeLfnmqOC5vEkU1JzOxerU', instagramUrl: 'https://instagram.com/madmonkeykohrong', tiktokUrl: 'https://tiktok.com/@madmonkey.kohrong', checkinUrl: 'https://fill.boloforms.com/signature/form/kohrong', wifi: { ssid: 'The Mad Monkey', password: 'jointhemadness', mobileconfig: '/wifi/kohrong.mobileconfig' } },
  { id: 'koh-sdach', name: 'Koh Sdach', country: 'Cambodia', category: PropertyCategory.BEACH, handle: 'kohsdach', slug: 'kohsdach-mother', whatsappUrl: 'https://chat.whatsapp.com/KcCxhxFGWISBS8qL6ZQ3Gw', instagramUrl: 'https://instagram.com/madmonkeykohsdach', tiktokUrl: 'https://tiktok.com/@madmonkeykohsdach', checkinUrl: 'https://fill.boloforms.com/signature/form/kohsdach', wifi: { ssid: 'reception', password: 'jointhemadness', mobileconfig: '/wifi/kohsdach.mobileconfig' } },
  { id: 'gili-t', name: 'Gili Trawangan', country: 'Indonesia', category: PropertyCategory.BEACH, handle: 'gilitrawangan', slug: 'gilit-mother', instagramUrl: 'https://instagram.com/madmonkeygilitrawangan', tiktokUrl: 'https://tiktok.com/@mad.monkey.gili.t', checkinUrl: 'https://fill.boloforms.com/signature/form/gilitrawangan', wifi: { ssid: 'MAD MONKEY BAR', password: 'jointhemadness', mobileconfig: '/wifi/gilitrawangan.mobileconfig' } },
  { id: 'kuta-lombok', name: 'Kuta Lombok', country: 'Indonesia', category: PropertyCategory.BEACH, handle: 'kutalombok', slug: 'kutalombok-mother', whatsappUrl: 'https://chat.whatsapp.com/FuOjWvIRMwBFFyoB0mKYDk', instagramUrl: 'https://instagram.com/madmonkeykutalombok', checkinUrl: 'https://fill.boloforms.com/signature/form/kutalombok', wifi: { ssid: 'MadMonkey2', password: 'jointhemadness', mobileconfig: '/wifi/kutalombok.mobileconfig' } },
  { id: 'uluwatu', name: 'Uluwatu', country: 'Indonesia', category: PropertyCategory.BEACH, handle: 'uluwatu', slug: 'uluwatu-mother', whatsappUrl: 'https://chat.whatsapp.com/Ke4ZrqDQGnFEXMNNlkuJsT', instagramUrl: 'https://instagram.com/madmonkeyuluwatu', checkinUrl: 'https://fill.boloforms.com/signature/form/uluwatu', wifi: { ssid: 'Mad Monkey', password: 'jointhemadness', mobileconfig: '/wifi/uluwatu.mobileconfig' } },
  { id: 'nusa-lembongan', name: 'Nusa Lembongan', country: 'Indonesia', category: PropertyCategory.BEACH, handle: 'nusalembongan', slug: 'nusalembongan-mother', whatsappUrl: 'https://chat.whatsapp.com/JT3T3XicKmTLaKKYM0yu7q?mode=gi_t', instagramUrl: 'https://instagram.com/madmonkeynusalembongan', checkinUrl: 'https://fill.boloforms.com/signature/form/nusalembongan', wifi: { ssid: 'MM Guest', password: 'jointhemadness', mobileconfig: '/wifi/nusalembongan.mobileconfig' } },
  { id: 'siargao', name: 'Siargao', country: 'Philippines', category: PropertyCategory.BEACH, handle: 'siargao', slug: 'siargao-mother', whatsappUrl: 'https://chat.whatsapp.com/BBLy7mC93WcBXD1pP6MYZU?mode=gi_t', instagramUrl: 'https://instagram.com/mad_monkey_siargao', checkinUrl: 'https://fill.boloforms.com/signature/form/siargao', wifi: { ssid: 'Mad Monkey', password: 'jointhemadness', mobileconfig: '/wifi/siargao.mobileconfig' } },
  { id: 'panglao', name: 'Panglao', country: 'Philippines', category: PropertyCategory.BEACH, handle: 'panglao', slug: 'panglao-mother', whatsappUrl: 'https://chat.whatsapp.com/BajoBLC3zsb0c7cfJj68Fl', checkinUrl: 'https://fill.boloforms.com/signature/form/panglao', wifi: { ssid: 'Mad Monkey Panglao', password: 'jointhemadness', mobileconfig: '/wifi/panglao.mobileconfig' } },
  { id: 'phuket', name: 'Phuket', country: 'Thailand', category: PropertyCategory.BEACH, handle: 'phuket', slug: 'phuket-mother', whatsappUrl: 'https://chat.whatsapp.com/KzqVcfLaDqF2NOoRcK4Rg2', instagramUrl: 'https://instagram.com/madmonkeyphuket', checkinUrl: 'https://fill.boloforms.com/signature/form/phuket', wifi: { ssid: 'Mad Monkey Phuket', password: 'jointhemadness', mobileconfig: '/wifi/phuket.mobileconfig' } },
  { id: 'chiang-mai', name: 'Chiang Mai', country: 'Thailand', category: PropertyCategory.ADVENTURE, handle: 'chiangmai', slug: 'chiangmai-mother', whatsappUrl: 'https://chat.whatsapp.com/IeqDN7Ayk5XCunHVNydDmm?mode=ac_t', instagramUrl: 'https://instagram.com/madmonkeychiangmai', tiktokUrl: 'https://tiktok.com/@madmonkeychiangmai', checkinUrl: 'https://fill.boloforms.com/signature/form/chiangmai', wifi: { ssid: 'Mad Monkey Chiang Mai', password: 'jointhemadness', mobileconfig: '/wifi/chiangmai.mobileconfig' } },
  { id: 'pai', name: 'Pai', country: 'Thailand', category: PropertyCategory.ADVENTURE, handle: 'pai', slug: 'pai-mother', whatsappUrl: 'https://chat.whatsapp.com/Fgt3kYmBGvkEAZYvE6FOAN', instagramUrl: 'https://instagram.com/madmonkey_pai', tiktokUrl: 'https://tiktok.com/@madmonkeyhostelspai', checkinUrl: 'https://fill.boloforms.com/signature/form/pai2', wifi: { ssid: 'Mad Monkey Pai', password: 'jointhemadness', mobileconfig: '/wifi/pai.mobileconfig' } },
  { id: 'hoi-an', name: 'Hoi An', country: 'Vietnam', category: PropertyCategory.ADVENTURE, handle: 'hoian', slug: 'hoian-mother', whatsappUrl: 'https://chat.whatsapp.com/LR00FjfBvZw9PWpA8v2N5L?mode=ac_t', instagramUrl: 'https://instagram.com/madmonkeyhoian', tiktokUrl: 'https://tiktok.com/@madmonkeyhoian', checkinUrl: 'https://fill.boloforms.com/signature/2449d864-bf0c-4b77-9a7e-aa0aa23a89a5?p=view&utm_source=Klaviyo&utm_medium=email&utm_campaign=Digital%20Check-in%20Hoi%20An&_kx=iMslowLricdieJVo0cCrng.WPVbfQ#googtrans(en)', wifi: { ssid: 'MAD MONKEY HOI AN', password: 'jointhemadness', mobileconfig: '/wifi/hoian.mobileconfig' } },
  { id: 'luang-prabang', name: 'Luang Prabang', country: 'Laos', category: PropertyCategory.ADVENTURE, handle: 'luangprabang', slug: 'luangprabang-mother', whatsappUrl: 'https://chat.whatsapp.com/J5cf5xgxZ3gIjucZ6nqCGE?mode=ac_t', instagramUrl: 'https://instagram.com/madmonkeyluangprabang', tiktokUrl: 'https://tiktok.com/@madmonkeyluangprabang', checkinUrl: 'https://fill.boloforms.com/signature/form/luangprabang', wifi: { ssid: 'MM bar', password: 'jointhemadness', mobileconfig: '/wifi/luangprabang.mobileconfig' } },
  { id: 'vang-vieng', name: 'Vang Vieng', country: 'Laos', category: PropertyCategory.ADVENTURE, handle: 'vangvieng', slug: 'vangvieng-mother', whatsappUrl: 'https://chat.whatsapp.com/DZFiLDqP3zuJIxxnnhnF7l?mode=ac_t', instagramUrl: 'https://instagram.com/madmonkeyvangvieng', tiktokUrl: 'https://tiktok.com/@madmonkeyvangvieng', checkinUrl: 'https://fill.boloforms.com/signature/form/vangvieng', wifi: { ssid: 'Madmonkey', password: 'jointhemadness', mobileconfig: '/wifi/vangvieng.mobileconfig' } },
  { id: 'siem-reap', name: 'Siem Reap', country: 'Cambodia', category: PropertyCategory.ADVENTURE, handle: 'siemreap', slug: 'siemreap-mother', whatsappUrl: 'https://chat.whatsapp.com/BYBQOX249Ok3kCmtQEbLo4', instagramUrl: 'https://instagram.com/madmonkeysiemreap_', tiktokUrl: 'https://tiktok.com/@madmonkey.siemreap', checkinUrl: 'https://fill.boloforms.com/signature/form/siemreap', wifi: { ssid: 'The Mad Monkey', password: 'jointhemadness', mobileconfig: '/wifi/siemreap.mobileconfig' } },
  { id: 'siquijor', name: 'Siquijor', country: 'Philippines', category: PropertyCategory.ADVENTURE, handle: 'siquijor', slug: 'siquijor-mother', instagramUrl: 'https://instagram.com/madmonkey_siquijor', checkinUrl: 'https://fill.boloforms.com/signature/form/siquijor', wifi: { ssid: 'mad monkey siquijor', password: 'jointhemadness', mobileconfig: '/wifi/siquijor.mobileconfig' } },
  { id: 'dumaguete', name: 'Dumaguete', country: 'Philippines', category: PropertyCategory.ADVENTURE, handle: 'dumaguete', slug: 'dumaguete-mother', instagramUrl: 'https://instagram.com/madmonkey_dumaguete', tiktokUrl: 'https://tiktok.com/@madmonkeydumaguete', checkinUrl: 'https://fill.boloforms.com/signature/form/dumaguete', wifi: { ssid: 'Mad Monkey Wifi', password: 'jointhemadness', mobileconfig: '/wifi/dumaguete.mobileconfig' } },
  { id: 'phnom-penh', name: 'Phnom Penh', country: 'Cambodia', category: PropertyCategory.CITY, handle: 'phnompenh', slug: 'phnompenh-mother', whatsappUrl: 'https://chat.whatsapp.com/ISFzdY6OEfPEnfhG6N8Jsa', instagramUrl: 'https://instagram.com/madmonkeyphnompenh', tiktokUrl: 'https://tiktok.com/@madmonkey.phnompenh', checkinUrl: 'https://fill.boloforms.com/signature/form/phnompenh', wifi: { ssid: 'Mad Monkey Phnom Penh', password: 'jointhemadness', mobileconfig: '/wifi/phnompenh.mobileconfig' } },
  { id: 'hanoi', name: 'Hanoi', country: 'Vietnam', category: PropertyCategory.HANOI, handle: 'hanoi', slug: 'hanoi-mother', whatsappUrl: 'https://chat.whatsapp.com/DpI7WUmVDizAfacDxXwzmw?mode=ac_t', instagramUrl: 'https://instagram.com/madmonkeyhanoi', tiktokUrl: 'https://tiktok.com/@madmonkeyhanoi', checkinUrl: 'https://fill.boloforms.com/signature/2449d864-bf0c-4b77-9a7e-aa0aa23a89a5?p=view#googtrans(en)', wifi: { ssid: 'MAD MONKEY G', password: 'jointhemadness', mobileconfig: '/wifi/hanoi.mobileconfig' } },
  { id: 'bangkok', name: 'Bangkok', country: 'Thailand', category: PropertyCategory.BANGKOK, handle: 'bangkok', slug: 'bangkok-mother', whatsappUrl: 'https://chat.whatsapp.com/Ep53YVu6knrDcdamdQuloD', instagramUrl: 'https://instagram.com/madmonkeybangkok', tiktokUrl: 'https://tiktok.com/@madmonkeybangkok', checkinUrl: 'https://fill.boloforms.com/signature/form/bangkok', wifi: { ssid: 'MADMONKEY-5G', password: 'jointhemadness', mobileconfig: '/wifi/bangkok.mobileconfig' } },
  { id: 'manila', name: 'Manila', country: 'Philippines', category: PropertyCategory.MANILA, handle: 'manila', slug: 'manila-mother', whatsappUrl: 'https://chat.whatsapp.com/Jk0b6DoNRhKFceolBZLj3h?mode=ac_t', instagramUrl: 'https://instagram.com/madmonkeymanila', checkinUrl: 'https://fill.boloforms.com/signature/form/manila', wifi: { ssid: 'Mad Monkey Manila', password: 'jointhemadness', mobileconfig: '/wifi/manila.mobileconfig' } },
  { id: 'nacpan-beach', name: 'Nacpan Beach', country: 'Philippines', category: PropertyCategory.BEACH, handle: 'nacpanbeach', slug: 'nacpanbeach-mother', whatsappUrl: 'https://chat.whatsapp.com/LcOhfBqA1VF1HxB6ldGHD1', checkinUrl: 'https://fill.boloforms.com/signature/form/nacpanbeach' }
];

export const CATEGORY_EMOJIS: Record<PropertyCategory, string> = {
  [PropertyCategory.BEACH]: '🏖️',
  [PropertyCategory.ADVENTURE]: '🌿',
  [PropertyCategory.CITY]: '🏙️',
  [PropertyCategory.HANOI]: '🇻🇳',
  [PropertyCategory.BANGKOK]: '🇹🇭',
  [PropertyCategory.MANILA]: '🇵🇭',
};
